#!/usr/bin/env bash
set -e
pair=uahrub
sources=(
  cbr
  privatbank_ua
)

case $1 in
  privatbank_ua) {
#    setzer x-price "$1" uahrub
    price=$(setzer x-price "$1" uahrub)
    setzer --format "$(bc -l <<<"1 / $price")"
  };;
  cbr ) {
#    price=$(setzer x-price "$1" uahrub)
#    setzer --format "$(bc -l <<<"1 / $price")"
    setzer x-price "$1" uahrub
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
