#!/usr/bin/env bash
set -e
pair=mdtmcr
sources=(
  uniswap_v2
)

case $1 in
  uniswap_v2) {
    eth_mdt=$(setzer price ethmdt "$1")
    eth_rub=$(setzer price ethrub)
    setzer --format "$(bc -l <<<"$eth_rub / $eth_mdt")"
  };;
  *) {
#    export SETZER_MIN_MEDIAN=2
#    setzer --price-commands "-$1-" $pair "${sources[@]}"
    eth_mdt=$(setzer price ethmdt "$1")
    eth_rub=$(setzer price ethrub)
    setzer --format "$(bc -l <<<"$eth_rub / $eth_mdt")"
  };;
esac
