#!/usr/bin/env bash
set -e
pair=btcmdt
sources=(
  uniswap_v2
)

case $1 in
  uniswap_v2) {
    eth_mdt=$(setzer price ethmdt "$1")
    eth_btc=$(setzer price ethbtc)
    setzer --format "$(bc -l <<<"$eth_mdt / $eth_btc")"
  };;
  *) {
#    export SETZER_MIN_MEDIAN=2
#    setzer --price-commands "-$1-" $pair "${sources[@]}"
    eth_mdt=$(setzer price ethmdt "$1")
    eth_btc=$(setzer price ethbtc)
    setzer --format "$(bc -l <<<"$eth_mdt / $eth_btc")"
  };;
esac

